#!/usr/bin/env zsh

STOW_FOLDERS="tmux,vim,bin"
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")

do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done

# Set scripts to be executable
find bin/.local/scripts -type f -exec chmod +x {} \;