matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y %H:%M"

  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - trigger: ":wt"
    replace: "{{weather}}"
    vars:
      - name: weather
        type: shell
        params:
          cmd: "curl -s 'wttr.in/Amsterdam?format=4'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/